name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv
        python -m virtualenv .env
        .env/bin/pip install -e .[testing]
    - name: Lint with pylint
      run: .env/bin/pylint -j 4 --rcfile=.pylintrc slash tests setup.py doc
    - name: Test with pytest
      run: .env/bin/pytest --cov=slash --cov-report=html tests

  win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m virtualenv .env
        .env/Scripts/pip.exe install -e .[testing,doc]
    - name: Lint with pylint
      run: .env/bin/pylint -j 4 --rcfile=.pylintrc slash tests setup.py doc
    - name: Test with pytest
      run: .env/Scripts/py.test.exe --cov=slash --cov-report=html tests

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv
        python -m virtualenv .env
        .env/bin/pip install -e .[doc]
    - name: Bulid documentation with Sphinx
      run: .env/bin/sphinx-build -a -W -E doc build/sphinx/html
